name: Deploy to Fly

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          ref: ${{ github.ref }}
          running-workflow-name: deploy
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --nixpacks
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
